import "@/styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { locales, mutableLocales, type Locale } from "@/lib/i18n";
import { getPages, getPagesInLocale } from "@/lib/helpers";
import LocaleSwitch from "./components/locale-switch.client";
import Nav from "./components/nav.server";
import styles from "./layout.module.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: Locale;
  };
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = params;

  if (!locales.includes(locale)) {
    return notFound();
  }

  const pages = await getPages();
  const pagesInLocale = getPagesInLocale(pages, locale);

  return (
    <html lang={locale}>
      <body className={clsx(inter.className, styles.layout)}>
        <header className={styles.topbar}>
          <LocaleSwitch
            locale={locale}
            locales={mutableLocales}
            includeCurrentLocale={true}
          />
        </header>

        <div className={styles.content}>
          <aside>
            <Nav locale={locale} pages={pagesInLocale} />
          </aside>

          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
